#######################################
# Imixs-AI
# llama-cpp image without GPU/CUDA support
#######################################
FROM python:3.10-bookworm

RUN CMAKE_ARGS="-DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS" pip install --upgrade llama-cpp-python

RUN pip install fastapi
RUN pip install "uvicorn[standard]"
RUN pip install fastapi-xml

COPY ./app /app
WORKDIR /app
      
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]