version: "3.6"
services:

#######################
# Imixs-AI
#######################
  app:
    image: imixs/imixs-ai-llama-cpp-cpu
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    #tty: true

    volumes: 
      - ./app:/app
      - ./models:/models
