# See: https://hub.docker.com/r/dustynv/llama_cpp#!

FROM dustynv/llama_cpp:gguf-r36.2.0

# Install fastAPI
RUN pip install fastapi
RUN pip install "uvicorn[standard]"
RUN pip install fastapi-xml

COPY ./app /app
WORKDIR /app


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]